const orders = [
  {
    orderId: "ORD-2001",
    customer: "Ahmed Khan",
    product: "Printer",
    date: "2025-08-10",
    amount: "1200 AED",
    status: "Delivered",
  },
  {
    orderId: "ORD-2002",
    customer: "Fatima Noor",
    product: "Tapes",
    date: "2025-08-12",
    amount: "45 AED",
    status: "Pending",
  },
  {
    orderId: "ORD-2003",
    customer: "Omar Ali",
    product: "Acrylic",
    date: "2025-08-14",
    amount: "320 AED",
    status: "Shipped",
  },
  {
    orderId: "ORD-2004",
    customer: "Sophia George",
    product: "Boards",
    date: "2025-08-15",
    amount: "600 AED",
    status: "Cancelled",
  },
  {
    orderId: "ORD-2005",
    customer: "Mohammed Rizwan",
    product: "Accessories",
    date: "2025-08-17",
    amount: "95 AED",
    status: "Delivered",
  },
  {
    orderId: "ORD-2006",
    customer: "Aisha Hassan",
    product: "Displays",
    date: "2025-08-19",
    amount: "750 AED",
    status: "Processing",
  },
  {
    orderId: "ORD-2007",
    customer: "David Paul",
    product: "Banners",
    date: "2025-08-21",
    amount: "280 AED",
    status: "Delivered",
  },
  {
    orderId: "ORD-2008",
    customer: "Lina Youssef",
    product: "Inks",
    date: "2025-08-22",
    amount: "150 AED",
    status: "Shipped",
  },
  {
    orderId: "ORD-2009",
    customer: "Karim Saleh",
    product: "Printer",
    date: "2025-08-24",
    amount: "1100 AED",
    status: "Pending",
  },
  {
    orderId: "ORD-2010",
    customer: "Emily Johnson",
    product: "Tapes",
    date: "2025-08-25",
    amount: "65 AED",
    status: "Delivered",
  },
];
 
export default orders;